
###
GET http://localhost:3000/
###

GET http://localhost:3000/football

###
GET http://localhost:3000/basketball

###
GET http://localhost:3000/regiones

###
GET  http://localhost:3000/categoria/1
###
GET http://localhost:3000/categoria/football
